import turtle
window = turtle.Screen()
geoff = turtle.Turtle()
t = turtle.Pen()
t.backward(100)
t.left(90)
t.up()
t.forward(30)
t.down()
t.right(90)
t.forward(100)
t.hideturtle()
t.reset() 
t.circle(50)
t.color('red')
t.circle(50)
window.exitonclick()